In [205]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

sns.set(style="whitegrid", palette="muted", font_scale=1.1)
%matplotlib inline

In [206]:
hungarian_path = os.path.join(os.getcwd(), '..', 'Data', 'raw', 'hungarian.data')
hungarian_df = pd.read_csv(hungarian_path, header=None)
va_path = os.path.join(os.getcwd(), '..', 'Data', 'raw', 'long-beach-va.data')
va_df = pd.read_csv(va_path, header=None)
switzerland_path = os.path.join(os.getcwd(), '..', 'Data', 'raw', 'switzerland.data')
switzerland_df = pd.read_csv(switzerland_path, header=None)
df = pd.concat([hungarian_df, switzerland_df, va_df], ignore_index=True)

In [207]:
def get_patients(path):
    patients = []

    with open(path) as f:
        lines = [line.strip() for line in f]

    current_values = []

    for line in lines:
        parts = line.split()

        if not parts:
            continue

        if "name" in parts:

            current_values.extend(parts)

            patients.append(current_values)

            current_values = []

        else:
            current_values.extend(parts)
    return patients

In [208]:
column_names = [
"id", "ccf", "age", "sex", "painloc", "painexer", "relrest", "pncaden", "cp",
"trestbps", "htn", "chol", "smoke", "cigs", "years", "fbs", "dm", "famhist", 
"restecg", "ekgmo", "ekgday", "ekgyr", "dig", "prop", "nitr", "pro", "diuretic",
"proto", "thaldur", "thaltime", "met", "thalach", "thalrest", "tpeakbps", 
"tpeakbpd", "dummy", "trestbpd", "exang", "xhypo", "oldpeak", "slope", "rldv5",
"rldv5e", "ca", "restckm", "exerckm", "restef", "restwm", "exeref", "exerwm",
"thal", "thalsev", "thalpul", "earlobe", "cmo", "cday", "cyr", "num", "lmt",
"ladprox", "laddist", "diag", "cxmain", "ramus", "om1", "om2", "rcaprox", 
"rcadist", "lvx1", "lvx2", "lvx3", "lvx4", "lvf", "cathef", "junk", "name"
]
hungarian_patients = get_patients(hungarian_path)
va_patients = get_patients(va_path)
switzerland_patients = get_patients(switzerland_path)

In [209]:

hungarian_df = pd.DataFrame(hungarian_patients, columns=column_names)
hungarian_df

,id,ccf,age,sex,painloc,painexer,relrest,pncaden,cp,trestbps,...,rcaprox,rcadist,lvx1,lvx2,lvx3,lvx4,lvf,cathef,junk,name
0,1254,0,40,1,1,0,0,-9,2,140,...,-9,-9,1,1,1,1,1,-9.,-9.,name
1,1255,0,49,0,1,0,0,-9,3,160,...,-9,-9,1,1,1,1,1,-9.,-9.,name
2,1256,0,37,1,1,0,0,-9,2,130,...,-9,-9,1,1,1,1,1,-9.,-9.,name
3,1257,0,48,0,1,1,1,-9,4,138,...,2,-9,1,1,1,1,1,-9.,-9.,name
4,1258,0,54,1,1,0,1,-9,3,150,...,1,-9,1,1,1,1,1,-9.,-9.,name
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,1053,0,48,0,0,0,0,-9,2,-9,...,-9,-9,1,1,1,1,1,-9.,-9.,name
290,1054,0,36,1,1,0,0,-9,2,120,...,-9,-9,1,1,1,1,1,-9.,-9.,name
291,5001,0,48,1,0,0,0,-9,3,110,...,-9,-9,1,1,1,1,1,-9.,-9.,name
292,5000,0,47,0,0,0,0,-9,2,140,...,-9,-9,1,1,1,1,1,-9.,-9.,name
293,5002,0,53,1,1,1,1,-9,4,130,...,1,1,1,1,1,1,1,-9.,-9.,name

In [210]:
va_df = pd.DataFrame(va_patients, columns=column_names)
va_df

,id,ccf,age,sex,painloc,painexer,relrest,pncaden,cp,trestbps,...,rcaprox,rcadist,lvx1,lvx2,lvx3,lvx4,lvf,cathef,junk,name
0,1,0,63,1,1,1,1,-9,4,140,...,2,1,1,1,1,1,1,0.7,5.5,name
1,2,0,44,1,1,1,1,-9,4,130,...,1,1,1,1,1,1,1,0.5,-9.,name
2,3,0,60,1,1,1,1,-9,4,132,...,2,1,1,1,1,7,2,0.52,4.1,name
3,4,0,55,1,1,1,1,-9,4,142,...,1,1,1,1,1,1,1,0.73,6.5,name
4,5,0,66,1,1,0,0,-9,3,110,...,1,1,1,1,1,1,1,0.73,8,name
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,200,0,54,0,1,1,1,-9,4,127,...,1,1,1,1,1,1,1,0.76,5.6,name
196,201,0,62,1,0,0,0,-9,1,-9,...,1,1,1,1,1,1,2,0.62,3.5,name
197,202,0,55,1,1,1,1,-9,4,122,...,2,1,1,1,1,1,1,0.69,5.6,name
198,116,0,58,1,1,1,1,-9,4,-9,...,1,1,1,1,1,1,1,0.81,6,name
199,160,0,62,1,1,0,0,-9,2,120,...,2,1,1,1,1,1,1,-9,-9.,name

In [211]:
switzerland_df = pd.DataFrame(switzerland_patients, columns=column_names)
switzerland_df

,id,ccf,age,sex,painloc,painexer,relrest,pncaden,cp,trestbps,...,rcaprox,rcadist,lvx1,lvx2,lvx3,lvx4,lvf,cathef,junk,name
0,3001,0,65,1,1,1,1,-9,4,115,...,1,1,1,1,1,1,1,75,-9.,name
1,3002,0,32,1,0,0,0,-9,1,95,...,1,1,1,1,1,5,1,63,-9.,name
2,3003,0,61,1,1,1,1,-9,4,105,...,2,1,1,1,1,1,1,67,-9.,name
3,3004,0,50,1,1,1,1,-9,4,145,...,1,1,1,1,1,5,4,36,-9.,name
4,3005,0,57,1,1,1,1,-9,4,110,...,2,1,1,1,1,1,1,60,-9.,name
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,4070,0,54,1,1,1,1,-9,4,180,...,1,1,1,1,1,1,1,71,-9.,name
119,4071,0,56,1,1,1,1,-9,4,125,...,2,1,5,1,1,1,2,68,-9.,name
120,4072,0,56,1,0,1,1,-9,3,125,...,1,1,1,1,5,3,2,61,-9.,name
121,4073,0,54,1,1,1,1,-9,4,130,...,2,1,1,1,1,1,1,-9.,-9.,name
122,4074,0,66,0,1,1,1,-9,4,155,...,2,1,1,1,1,1,1,70,-9.,name

In [212]:
df = pd.concat([hungarian_df, va_df, switzerland_df])
df

,id,ccf,age,sex,painloc,painexer,relrest,pncaden,cp,trestbps,...,rcaprox,rcadist,lvx1,lvx2,lvx3,lvx4,lvf,cathef,junk,name
0,1254,0,40,1,1,0,0,-9,2,140,...,-9,-9,1,1,1,1,1,-9.,-9.,name
1,1255,0,49,0,1,0,0,-9,3,160,...,-9,-9,1,1,1,1,1,-9.,-9.,name
2,1256,0,37,1,1,0,0,-9,2,130,...,-9,-9,1,1,1,1,1,-9.,-9.,name
3,1257,0,48,0,1,1,1,-9,4,138,...,2,-9,1,1,1,1,1,-9.,-9.,name
4,1258,0,54,1,1,0,1,-9,3,150,...,1,-9,1,1,1,1,1,-9.,-9.,name
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,4070,0,54,1,1,1,1,-9,4,180,...,1,1,1,1,1,1,1,71,-9.,name
119,4071,0,56,1,1,1,1,-9,4,125,...,2,1,5,1,1,1,2,68,-9.,name
120,4072,0,56,1,0,1,1,-9,3,125,...,1,1,1,1,5,3,2,61,-9.,name
121,4073,0,54,1,1,1,1,-9,4,130,...,2,1,1,1,1,1,1,-9.,-9.,name
122,4074,0,66,0,1,1,1,-9,4,155,...,2,1,1,1,1,1,1,70,-9.,name

# Step 2: Data Cleaning Workflow
## 1/ Inspect the Data Structure

In [213]:
df.shape
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 617 entries, 0 to 122
Data columns (total 76 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        617 non-null    object
 1   ccf       617 non-null    object
 2   age       617 non-null    object
 3   sex       617 non-null    object
 4   painloc   617 non-null    object
 5   painexer  617 non-null    object
 6   relrest   617 non-null    object
 7   pncaden   617 non-null    object
 8   cp        617 non-null    object
 9   trestbps  617 non-null    object
 10  htn       617 non-null    object
 11  chol      617 non-null    object
 12  smoke     617 non-null    object
 13  cigs      617 non-null    object
 14  years     617 non-null    object
 15  fbs       617 non-null    object
 16  dm        617 non-null    object
 17  famhist   617 non-null    object
 18  restecg   617 non-null    object
 19  ekgmo     617 non-null    object
 20  ekgday    617 non-null    object
 21  ekgyr     617 non-null    object
 22  dig       617 non-null    object
 23  prop      617 non-null    object
 24  nitr      617 non-null    object
 25  pro       617 non-null    object
 26  diuretic  617 non-null    object
 27  proto     617 non-null    object
 28  thaldur   617 non-null    object
 29  thaltime  617 non-null    object
 30  met       617 non-null    object
 31  thalach   617 non-null    object
 32  thalrest  617 non-null    object
 33  tpeakbps  617 non-null    object
 34  tpeakbpd  617 non-null    object
 35  dummy     617 non-null    object
 36  trestbpd  617 non-null    object
 37  exang     617 non-null    object
 38  xhypo     617 non-null    object
 39  oldpeak   617 non-null    object
 40  slope     617 non-null    object
 41  rldv5     617 non-null    object
 42  rldv5e    617 non-null    object
 43  ca        617 non-null    object
 44  restckm   617 non-null    object
 45  exerckm   617 non-null    object
 46  restef    617 non-null    object
 47  restwm    617 non-null    object
 48  exeref    617 non-null    object
 49  exerwm    617 non-null    object
 50  thal      617 non-null    object
 51  thalsev   617 non-null    object
 52  thalpul   617 non-null    object
 53  earlobe   617 non-null    object
 54  cmo       617 non-null    object
 55  cday      617 non-null    object
 56  cyr       617 non-null    object
 57  num       617 non-null    object
 58  lmt       617 non-null    object
 59  ladprox   617 non-null    object
 60  laddist   617 non-null    object
 61  diag      617 non-null    object
 62  cxmain    617 non-null    object
 63  ramus     617 non-null    object
 64  om1       617 non-null    object
 65  om2       617 non-null    object
 66  rcaprox   617 non-null    object
 67  rcadist   617 non-null    object
 68  lvx1      617 non-null    object
 69  lvx2      617 non-null    object
 70  lvx3      617 non-null    object
 71  lvx4      617 non-null    object
 72  lvf       617 non-null    object
 73  cathef    617 non-null    object
 74  junk      617 non-null    object
 75  name      617 non-null    object
dtypes: object(76)
memory usage: 371.2+ KB

## 2/ Standardize Missing Values

In [214]:
import numpy as np

df.replace("?", np.nan, inplace=True)
df.replace("NA", np.nan, inplace=True)
df.replace("-9", np.nan, inplace=True)

df.isna().sum()

C:\Users\hcant\AppData\Local\Temp\ipykernel_20780\3604265297.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("-9", np.nan, inplace=True)

id          0
ccf         0
age         0
sex         0
painloc     0
           ..
lvx4       19
lvf        16
cathef     24
junk        1
name        0
Length: 76, dtype: int64

## 3/ Convert Data Types

In [215]:
df = df.apply(pd.to_numeric, errors="ignore")
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 617 entries, 0 to 122
Data columns (total 76 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        617 non-null    int64
 1   ccf       617 non-null    int64
 2   age       617 non-null    int64
 3   sex       617 non-null    int64
 4   painloc   617 non-null    int64
 5   painexer  617 non-null    int64
 6   relrest   613 non-null    float64
 7   pncaden   0 non-null      float64
 8   cp        617 non-null    int64
 9   trestbps  558 non-null    float64
 10  htn       583 non-null    float64
 11  chol      587 non-null    float64
 12  smoke     230 non-null    float64
 13  cigs      202 non-null    float64
 14  years     190 non-null    float64
 15  fbs       527 non-null    float64
 16  dm        72 non-null     float64
 17  famhist   195 non-null    float64
 18  restecg   615 non-null    float64
 19  ekgmo     564 non-null    float64
 20  ekgday    563 non-null    float64
 21  ekgyr     564 non-null    float64
 22  dig       551 non-null    float64
 23  prop      553 non-null    float64
 24  nitr      554 non-null    float64
 25  pro       556 non-null    float64
 26  diuretic  537 non-null    float64
 27  proto     505 non-null    float64
 28  thaldur   561 non-null    float64
 29  thaltime  233 non-null    float64
 30  met       512 non-null    float64
 31  thalach   562 non-null    float64
 32  thalrest  561 non-null    float64
 33  tpeakbps  554 non-null    float64
 34  tpeakbpd  554 non-null    float64
 35  dummy     558 non-null    float64
 36  trestbpd  558 non-null    float64
 37  exang     562 non-null    float64
 38  xhypo     559 non-null    float64
 39  oldpeak   555 non-null    float64
 40  slope     309 non-null    float64
 41  rldv5     474 non-null    float64
 42  rldv5e    475 non-null    float64
 43  ca        11 non-null     float64
 44  restckm   0 non-null      float64
 45  exerckm   1 non-null      float64
 46  restef    28 non-null     float64
 47  restwm    30 non-null     float64
 48  exeref    2 non-null      float64
 49  exerwm    5 non-null      float64
 50  thal      142 non-null    float64
 51  thalsev   130 non-null    float64
 52  thalpul   44 non-null     float64
 53  earlobe   1 non-null      float64
 54  cmo       606 non-null    float64
 55  cday      608 non-null    float64
 56  cyr       608 non-null    float64
 57  num       617 non-null    int64
 58  lmt       342 non-null    float64
 59  ladprox   381 non-null    float64
 60  laddist   371 non-null    float64
 61  diag      341 non-null    float64
 62  cxmain    382 non-null    float64
 63  ramus     332 non-null    float64
 64  om1       346 non-null    float64
 65  om2       327 non-null    float64
 66  rcaprox   372 non-null    float64
 67  rcadist   347 non-null    float64
 68  lvx1      598 non-null    float64
 69  lvx2      598 non-null    float64
 70  lvx3      598 non-null    float64
 71  lvx4      598 non-null    float64
 72  lvf       601 non-null    float64
 73  cathef    593 non-null    float64
 74  junk      616 non-null    float64
 75  name      617 non-null    object
dtypes: float64(67), int64(8), object(1)
memory usage: 371.2+ KB

C:\Users\hcant\AppData\Local\Temp\ipykernel_20780\2304015745.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")

## 4/ Remove Irrelevant Columns

In [216]:
irrelevant_cols = ["id", "ccf", "dummy", "lvx1", "lvx2", "lvx3", "lvx4", "lvf", "cathef", "junk", "name", "thalsev", "thalpul", "earlobe", "restckm", "exerckm"]
df.drop(columns=irrelevant_cols, inplace=True)
df

,age,sex,painloc,painexer,relrest,pncaden,cp,trestbps,htn,chol,...,lmt,ladprox,laddist,diag,cxmain,ramus,om1,om2,rcaprox,rcadist
0,40,1,1,0,0.0,NaN,2,140.0,0.0,289.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,49,0,1,0,0.0,NaN,3,160.0,1.0,180.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,37,1,1,0,0.0,NaN,2,130.0,0.0,283.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,48,0,1,1,1.0,NaN,4,138.0,0.0,214.0,...,NaN,2.0,NaN,NaN,2.0,NaN,NaN,NaN,2.0,NaN
4,54,1,1,0,1.0,NaN,3,150.0,0.0,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,54,1,1,1,1.0,NaN,4,180.0,0.0,0.0,...,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
119,56,1,1,1,1.0,NaN,4,125.0,0.0,0.0,...,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0
120,56,1,0,1,1.0,NaN,3,125.0,0.0,0.0,...,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0
121,54,1,1,1,1.0,NaN,4,130.0,0.0,0.0,...,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0
122,66,0,1,1,1.0,NaN,4,155.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0

## 5/Handle Missing Data

In [217]:
missing_percentage = (df.isna().sum() / len(df)) * 100
missing_percentage.sort_values(ascending=False)

pncaden     100.000000
exeref       99.675851
exerwm       99.189627
ca           98.217180
restef       95.461912
restwm       95.137763
dm           88.330632
thal         76.985413
years        69.205835
famhist      68.395462
cigs         67.260940
smoke        62.722853
thaltime     62.236629
slope        49.918963
om2          47.001621
ramus        46.191248
diag         44.732577
lmt          44.570502
om1          43.922204
rcadist      43.760130
laddist      39.870340
rcaprox      39.708266
ladprox      38.249595
cxmain       38.087520
rldv5        23.176661
rldv5e       23.014587
proto        18.152350
met          17.017828
fbs          14.586710
diuretic     12.965964
dig          10.696921
prop         10.372771
tpeakbpd     10.210697
tpeakbps     10.210697
nitr         10.210697
oldpeak      10.048622
pro           9.886548
trestbps      9.562399
trestbpd      9.562399
xhypo         9.400324
thaldur       9.076175
thalrest      9.076175
thalach       8.914100
exang         8.914100
ekgday        8.752026
ekgmo         8.589951
ekgyr         8.589951
htn           5.510535
chol          4.862237
cmo           1.782820
cyr           1.458671
cday          1.458671
relrest       0.648298
restecg       0.324149
painexer      0.000000
age           0.000000
cp            0.000000
painloc       0.000000
sex           0.000000
num           0.000000
dtype: float64

## 6/Remove Duplicate Rows

In [218]:
df = df.drop_duplicates()

## 7/ Validate Value Ranges

In [219]:
df.describe()

,age,sex,painloc,painexer,relrest,pncaden,cp,trestbps,htn,chol,...,lmt,ladprox,laddist,diag,cxmain,ramus,om1,om2,rcaprox,rcadist
count,617.000000,617.000000,617.000000,617.000000,613.000000,0.0,617.000000,558.000000,583.000000,587.000000,...,342.000000,381.000000,371.000000,341.000000,382.000000,332.000000,346.000000,327.000000,372.000000,347.000000
mean,53.055105,0.842788,0.920583,0.593193,0.672104,NaN,3.294976,132.372760,0.408233,174.579216,...,1.555556,1.464567,1.280323,1.202346,1.400524,1.114458,1.187861,1.067278,1.470430,1.207493
std,9.582869,0.364296,0.270607,0.491637,0.469830,NaN,0.913743,19.828097,0.491929,124.349962,...,8.706091,0.499399,0.449764,0.402339,0.490647,0.318847,0.391167,0.250887,0.499797,0.406097
min,28.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,47.000000,1.000000,1.000000,0.000000,0.000000,NaN,3.000000,120.000000,0.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,54.000000,1.000000,1.000000,1.000000,1.000000,NaN,4.000000,130.000000,0.000000,214.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,60.000000,1.000000,1.000000,1.000000,1.000000,NaN,4.000000,142.000000,1.000000,263.000000,...,1.000000,2.000000,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,2.000000,1.000000
max,77.000000,1.000000,1.000000,1.000000,1.000000,NaN,4.000000,200.000000,1.000000,603.000000,...,162.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000

## 9/ Check Unique Values

In [220]:
for col in df.columns:
    print(col, df[col].nunique())

age 50
sex 2
painloc 2
painexer 2
relrest 2
pncaden 0
cp 4
trestbps 52
htn 2
chol 182
smoke 2
cigs 14
years 26
fbs 2
dm 2
famhist 2
restecg 3
ekgmo 12
ekgday 31
ekgyr 7
dig 2
prop 3
nitr 2
pro 2
diuretic 2
proto 14
thaldur 56
thaltime 56
met 28
thalach 106
thalrest 68
tpeakbps 60
tpeakbpd 40
trestbpd 29
exang 2
xhypo 2
oldpeak 39
slope 4
rldv5 31
rldv5e 30
ca 4
restef 24
restwm 4
exeref 2
exerwm 2
thal 7
cmo 12
cday 31
cyr 10
num 5
lmt 4
ladprox 2
laddist 2
diag 2
cxmain 2
ramus 2
om1 2
om2 2
rcaprox 2
rcadist 2

In [221]:
## 8/ Check Categorical Variables
## 10/ Verify Final Dataset