# 1 Dataset Loading

In [26]:
import pandas as pd
import os


clean_heart_disease_data_path = os.path.join(os.getcwd(), '..', 'Data', 'processed', 'clean_heart_disease.data')
df = pd.read_csv(clean_heart_disease_data_path, sep=',')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,40,1,2,140.0,289.0,0.0,0.0,172.0,0.0,0.0,NaN,NaN,NaN,0
1,49,0,3,160.0,180.0,0.0,0.0,156.0,0.0,1.0,2.0,NaN,NaN,1
2,37,1,2,130.0,283.0,0.0,1.0,98.0,0.0,0.0,NaN,NaN,NaN,0
3,48,0,4,138.0,214.0,0.0,0.0,108.0,1.0,1.5,2.0,NaN,NaN,3
4,54,1,3,150.0,NaN,0.0,0.0,122.0,0.0,0.0,NaN,NaN,NaN,0

# 2 Feature Type Identification

In [27]:
target = "num"

numerical_features = [
    "age",
    "trestbps",
    "chol",
    "thalach",
    "oldpeak"
]

binary_features = [
    "sex",
    "fbs",
    "exang"
]

categorical_features = [
    "cp",
    "restecg",
    "slope",
    "thal",
    "ca"
]

In [28]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,40,1,2,140.0,289.0,0.0,0.0,172.0,0.0,0.0,NaN,NaN,NaN,0
1,49,0,3,160.0,180.0,0.0,0.0,156.0,0.0,1.0,2.0,NaN,NaN,1
2,37,1,2,130.0,283.0,0.0,1.0,98.0,0.0,0.0,NaN,NaN,NaN,0
3,48,0,4,138.0,214.0,0.0,0.0,108.0,1.0,1.5,2.0,NaN,NaN,3
4,54,1,3,150.0,NaN,0.0,0.0,122.0,0.0,0.0,NaN,NaN,NaN,0

# 3 Encoding Categorical Features

In [29]:
df_encoded = pd.get_dummies(
    df,
    columns=categorical_features,
    drop_first=True
)

df_encoded.head()

,age,sex,trestbps,chol,fbs,thalach,exang,oldpeak,num,cp_2,...,slope_3.0,thal_2.0,thal_3.0,thal_4.0,thal_5.0,thal_6.0,thal_7.0,ca_1.0,ca_2.0,ca_9.0
0,40,1,140.0,289.0,0.0,172.0,0.0,0.0,0,True,...,False,False,False,False,False,False,False,False,False,False
1,49,0,160.0,180.0,0.0,156.0,0.0,1.0,1,False,...,False,False,False,False,False,False,False,False,False,False
2,37,1,130.0,283.0,0.0,98.0,0.0,0.0,0,True,...,False,False,False,False,False,False,False,False,False,False
3,48,0,138.0,214.0,0.0,108.0,1.0,1.5,3,False,...,False,False,False,False,False,False,False,False,False,False
4,54,1,150.0,NaN,0.0,122.0,0.0,0.0,0,False,...,False,False,False,False,False,False,False,False,False,False

# 4 Feature Scaling

# 5 Feature Validation

# 6 Final Feature Matrix